apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
spec:
  mode: deployment
  image: otel/opentelemetry-collector-contrib:latest
  config: |
    receivers:
      otlp:
        protocols:
          grpc: 

    processors:
      batch:
        timeout: 1s

      resource:
        attributes:
          - key: k8s.cluster.name
            from_attribute: k8s-cluster
            action: insert

    exporters:
      otlp:
        endpoint: simplest-collector.observability.svc:4317

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [resource, batch]
          exporters: [otlp]
    |

