apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: integration-tracetest-job
  namespace: argocd
spec:
  destination:
    namespace: tracetest
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/adnanrahic/demo-apiops-observability'
    path: staging/tracetest
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
