apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-collector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/SonjaChevre/demo-apiops-observability'
    path: staging/opentelemetry-collector
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: observability

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
