apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-redis-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 17.11.3
    helm:
      parameters:
        - name: image.tag
          value: 6.2.13
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tyk

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
