apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apis-parent-application
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/SonjaChevre/demo-apiops-observability'
    path: staging/argocd-apis
    targetRevision: sonja-production
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
