apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: httpbin
spec:
  name: httpbin
  use_keyless: true
  protocol: http
  active: true
  detailed_tracing: true
  proxy:
    target_url: go-httpbin-service.go-httpbin.svc.cluster.local:8070
    listen_path: /httpbin
    strip_listen_path: true