apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-definitions
  namespace: argocd
spec:
  destination:
    namespace: tyk
    server: https://kubernetes.default.svc
  project: apis
  source:
    repoURL: 'https://github.com/SonjaChevre/demo-apiops-observability.git'
    path: staging/api-definitions
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
